// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/anaknegeri/agent-session/internal/application/ports"
	"github.com/anaknegeri/agent-session/internal/application/services"
	"github.com/anaknegeri/agent-session/internal/providers"
	"github.com/google/wire"
	"log/slog"
)

// Injectors from wire.go:

// InitializeApp wires the application with a runtime store.
func InitializeApp(store ports.Store, logger *slog.Logger, budget ports.ContextBudget) (*services.App, error) {
	gitService := providers.ProvideGitService()
	initService := providers.ProvideInitService(store, gitService, logger)
	sessionService := providers.ProvideSessionService(store, gitService, logger)
	taskService := providers.ProvideTaskService(store, logger)
	decisionService := providers.ProvideDecisionService(store, logger)
	eventService := providers.ProvideEventService(store)
	workspaceService := providers.ProvideWorkspaceService(gitService)
	checkpointService := providers.ProvideCheckpointService(store, gitService, logger)
	contextRenderer := providers.ProvideRenderer()
	artifactService := providers.ProvideArtifactService(store)
	syncService := providers.ProvideSyncService(store, gitService, artifactService, logger)
	contextService := providers.ProvideContextService(store, checkpointService, contextRenderer, budget, syncService)
	handoffService := providers.ProvideHandoffService(store, checkpointService, contextRenderer, budget, logger)
	memoryService := providers.ProvideMemoryService(store, logger)
	exportService := providers.ProvideExportService(store)
	app := providers.ProvideApp(initService, sessionService, taskService, decisionService, eventService, workspaceService, checkpointService, contextService, handoffService, artifactService, memoryService, exportService, syncService, store)
	return app, nil
}

// wire.go:

var appSet = wire.NewSet(providers.ProvideInitService, providers.ProvideSessionService, providers.ProvideTaskService, providers.ProvideDecisionService, providers.ProvideEventService, providers.ProvideWorkspaceService, providers.ProvideCheckpointService, providers.ProvideContextService, providers.ProvideHandoffService, providers.ProvideArtifactService, providers.ProvideMemoryService, providers.ProvideExportService, providers.ProvideSyncService, providers.ProvideRenderer, providers.ProvideGitService, providers.ProvideApp)
