#!/usr/bin/env bash
set -euo pipefail

# update-homebrew-formula.sh — regenerate packaging/Homebrew/agent-session.rb
# with the current version and SHA256 checksums from local dist binaries.
#
# Requires: dist binaries already built (make cross-compile).
# Works with bash 3.2 (macOS default).
# After regenerating, publish the formula to your Homebrew tap.

cd "$(dirname "$0")/.."

version_tag="$(./scripts/version.sh)"
version="${version_tag#v}"
dir="packaging/Homebrew"

[ -d "dist" ] || { echo "error: no dist/ — run make cross-compile first" >&2; exit 1; }

sha256_for() {
  shasum -a 256 "dist/$1" 2>/dev/null | awk '{print $1}'
}

darwin_arm64=$(sha256_for agent-session-darwin-arm64)
darwin_amd64=$(sha256_for agent-session-darwin-amd64)
linux_arm64=$(sha256_for agent-session-linux-arm64)
linux_amd64=$(sha256_for agent-session-linux-amd64)
mcp_darwin_arm64=$(sha256_for agent-session-mcp-darwin-arm64)
mcp_darwin_amd64=$(sha256_for agent-session-mcp-darwin-amd64)
mcp_linux_arm64=$(sha256_for agent-session-mcp-linux-arm64)
mcp_linux_amd64=$(sha256_for agent-session-mcp-linux-amd64)

cat > "$dir/agent-session.rb" <<EOF
# Homebrew formula for Agent Session (macOS + Linux via Linuxbrew).
# Generated by scripts/update-homebrew-formula.sh — do not edit manually.
# Publish to your tap: gh repo create anaknegeri/homebrew-tap --public && cp this to Formula/
class AgentSession < Formula
  desc "Universal session & handoff layer for AI coding agents"
  homepage "https://agent-session.dev"
  license "MIT"
  version "${version}"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-darwin-arm64"
      sha256 "${darwin_arm64}"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-mcp-darwin-arm64"
        sha256 "${mcp_darwin_arm64}"
      end
    else
      url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-darwin-amd64"
      sha256 "${darwin_amd64}"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-mcp-darwin-amd64"
        sha256 "${mcp_darwin_amd64}"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-linux-arm64"
      sha256 "${linux_arm64}"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-mcp-linux-arm64"
        sha256 "${mcp_linux_arm64}"
      end
    else
      url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-linux-amd64"
      sha256 "${linux_amd64}"
      resource "mcp" do
        url "https://github.com/anaknegeri/agent-session/releases/download/v${version}/agent-session-mcp-linux-amd64"
        sha256 "${mcp_linux_amd64}"
      end
    end
  end

  def install
    bin.install Dir["agent-session-*"].find { |f| !f.include?("mcp") } => "agent-session"
    resource("mcp").stage { bin.install Dir["agent-session-mcp-*"].first => "agent-session-mcp" }
  end

  test do
    assert_match "agent-session", shell_output("#{bin}/agent-session --help")
  end
end
EOF

echo "wrote $dir/agent-session.rb (version ${version})"
